# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name CyclicVariationalCausalDiscovery
#' @title CyclicVariationalCausalDiscovery
#' @description This class provides a variational inference algorithm for cyclic structrual equation models
#' @field new Constructor
NULL

